packages:
  - internal
  - apps/*
  - packages/*

catalog:
  '@types/react': ^19.1.0
  '@types/react-dom': ^19.1.0
  '@types/node': ^22.16.0
  vite: ^7.0.3
  eslint: ^9.30.1
  typescript: ^5.8.3
  tsdown: 0.12.9
  react: ^19.1.0
  react-dom: ^19.1.0
  tailwindcss: 4.1.11
  '@tailwindcss/cli': ^4.1.11
  postcss: ^8.5.6
  autoprefixer: ^10.4.21
